# Nombre del proyecto y descripción
name: lecto_02
description: Una aplicación para convertir texto a voz.

# Configuración de publicación
publish_to: 'none' # Evita publicar el paquete en pub.dev

# Configuración de versión
version: 1.0.1+2 # Versión de la app: [versión]+[build]

# Entorno requerido
environment:
  sdk: '>=2.19.0 <3.0.0' # Versión del SDK de Dart requerida

# Dependencias principales
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0 # Gestión de estado
  easy_localization: ^3.0.0 # Localización
  http: ^0.13.5 # Solicitudes HTTP
  url_launcher: ^6.1.5 # Abrir enlaces en el navegador
  flutter_bloc: ^8.1.1 # Gestión de estado con BLoC
  equatable: ^2.0.5 # Comparaciones de igualdad simplificadas
  just_audio: ^0.9.30 # Reproducción de audio
  file_picker: ^5.2.5 # Selección de archivos
  path_provider: ^2.0.11 # Acceso a directorios del sistema
  shared_preferences: ^2.0.15 # Almacenamiento local de datos
  flutter_pdfview: ^1.2.5 # Visualización de PDFs

# Dependencias para desarrollo
dev_dependencies:
  flutter_test:
    sdk: flutter # Framework para pruebas de Flutter
  flutter_lints: ^2.0.0 # Estándares de código

# Configuraciones adicionales de Flutter
flutter:
  uses-material-design: true
  assets:
    - assets/translations/ # Traducciones
    - assets/images/ # Imágenes

  # Para agregar fuentes personalizadas a tu aplicación, añade una sección de fuentes aquí,
  # en esta sección "flutter". Cada entrada en esta lista debe tener una
  # clave "family" con el nombre de la familia de fuentes, y una clave "fonts" con una
  # lista que proporcione el asset y otros descriptores para la fuente.
  #
  # Por ejemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
